### PR TITLE
New syntax support

### PR DESCRIPTION
**Pull request by TiBarification**
And added missing "Natives as optional"

### CODE REVIEW

**Comment by KyleSanderson** [comment]
I'll take the missing natives for sure. The new syntax; I still personally use the SM1.6 compiler so this would"break my shit". Not against it, but if you use defines that would be great.

**Comment by TiBarification** [comment]
Now syntax divided on 2 files. Or put them into one file but add `#if` statements to one file?

**Comment by KyleSanderson** [comment]
I'd keep them in the same file. Can you please check the major version too?

**Comment by TiBarification** [comment]
In one file it is pretty hard to understand api. Need a good documentation. Maybe wiki?

**Comment by sneak-it** [comment]
@KyleSanderson Is it about time to update this to new syntax, now that the 1.10 compiler requires it?

**Comment by KyleSanderson** [comment]
21:35:48 <KyleS> oh my god is sneak only on Discord...
21:36:23 <KyleS> and no, there's no way that 1.10 is newdecls only; that would be r-'d into oblivion.

**Pull request closed without merging**
