### PR TITLE
Update AMBuild install script to conform with new requirements.

### PR DESCRIPTION
**Pull request by WildCard65**
See: alliedmodders/ambuild#68

### CODE REVIEW

**Comment by KyleSanderson** [comment]
There's certainly a better way to handle this @WildCard65 . Breaking every single consumer out there is bullshit - this is not okay.

@dvander what do you think?

**Comment by WildCard65** [comment]
@KyleSanderson This is mostly out of our hands as the original method is being deprecated and removed in the future, both distutils being a standard library in Python and usage of ```setup.py install```

**Comment by WildCard65** [comment]
Things to note:

   - "distutils" is extremely rarely updated within Python, this has to problems with setuptools as they have to monkey patch in fixes.
   - "setuptools" are planning on deprecating and then erroring usage of ```setup.py install``` once they finish the merging of distutils into setuptools.
   - "distutils" may eventually no longer be available with newer Python versions unless the installation has "setuptools"
   - "pip" is the Python community accepted standard of installing packages in Python, heck, PEP 517 is a proposal to further disconnect "pip" from setuptools/```setup.py```

**Comment by WildCard65** [comment]
Requesting @pganssle for assistance in explaining.

**Comment by dvander** [comment]
To be clear: no, it's not "out of our hands". When something is deprecated, that applies to new systems, not to old ones. As you've experienced firsthand, it's not a winning proposition to break every downstream consumer. There has to be a transition path.

In retrospect, CI should have been using tagged ambuild releases. That's partially on me for not encouraging it, but it's something we should do in the future.

**Comment by pganssle** [comment]
I don't really have much to say here, but I can confirm that you should absolutely not be using `setup.py install`, I would be surprised if whatever systems you've been using it with are not already broken in at least subtle ways. There is no ongoing support for `setup.py install`, either on setuptools or in distutils. My understanding is that you see some breakage in systems that are updated after they've been installed with `setup.py install` when you try to use `pip`. This is one example of the kind of bugs you will see if you use `setup.py install`.

I don't have much of a dog in the fight here; obviously I prefer if you use the supported path because it reduces support burden when your users find that their Python installation is broken and try to report it to setuptools or CPython, but it doesn't take much effort to say, "Sorry, we don't support that anymore" and close the ticket.

I hope you can find a satisfactory upgrade path with minimal disruption.

**Comment by WildCard65** [comment]
Thank you for your input @pganssle

**Comment by KyleSanderson** [comment]
Thank you for joining the conversation @pganssle . It looks like 6 years ago AlliedMods LLC started using `setup.py install` as part of their build pipeline while they were still on Mercurial.

Please see: https://hg.alliedmods.net/sourcemod-central/file/b9d5c01a5a3b/tools/checkout-deps.sh#l100

I'm pretty conflicted here. Prior to the destructive change the upstream project I rely on was humming along. Now all of a sudden, as if a bomb as gone off, every single repository per @WildCard65 is horifically broken with a previously very stable API (and lets face it, ABI as well). Do we have a clear reason why we're destroying open-source code left right and center by this change? Shouldn't this be transparently handled by an upstream library? Is this not 7 lines of script in python to resolve (which is 2 branches for installing the required modules)?

**Comment by WildCard65** [comment]
Part of the problem is not all Python installs have setuptools/pip pre-installed as by technicality, it's optional.
Some distributions (Ubuntu 20.04 for example) do have setuptools installed, but not pip.
Recent Python Windows Installers do include a bundled copy of pip which also includes setuptools and wheel, but it's an optional feature.

There has to be a limit to backwards compatibility, and it appears we '''may''' be approaching this limit for AMBuild as forwards compatibility is also something to keep in mind.

**Comment by WildCard65** [comment]
@KyleSanderson An alternative for now is to reject this PR and pin AMBuild to commit "0db7a7d8d0869c1d70159d9d0fa168ae48e615be" via ```git checkout 0db7a7d8d0869c1d70159d9d0fa168ae48e615be```

**Comment by KyleSanderson** [comment]
hi Team ( @WildCard65 and @pganssle ),

This has been resolved by: https://github.com/KyleSanderson/SteamWorks/commit/6801504424539bf43ea69f4f0b14a28d1047cbc3

Thanks for your comments on this one.

**Comment by pganssle** [comment]
Very rude and inaccurate commit message, by the way.

**Pull request closed without merging**
